A biblioteca pandas é importante para leitura do arquivo.

In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df_principal = pd.read_excel("acoes_pura.xlsx", sheet_name="Principal")
df_principal

c:\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Ativo,Data,Último (R$),Var. Dia (%),Var. Sem. (%),Var. Mês (%),Var. Ano (%),Var. 12M (%),Val. Mín,Val. Máx,Volume,Variação (%),Valor Inicial (R$),Qntd de ações,Variação (R$),Resultado,Nome da empresa,Segmento,Idade,Cat. Idade
0,USIM5,2024-01-26,9.50,5.20,11.76,2.26,2.26,15.97,9.18,9.56,"319,16 M",0.0520,9.030418,515117391,2.418897e+08,SUBIU,Usiminas,Siderurgia,62,ENTRE 50 E 100
1,CMIN3,2024-01-26,6.82,2.40,2.40,-12.11,-12.11,50.56,6.66,6.86,"32,65 M",0.0240,6.660156,1110559345,1.775160e+08,SUBIU,CSN Mineração,Mineração,20,MENOS DE 50
2,PETR3,2024-01-26,41.96,2.19,7.73,7.64,7.64,77.55,40.81,42.34,"436,69 M",0.0219,41.060769,2379877655,2.140059e+09,SUBIU,Petrobras,Petróleo,69,ENTRE 50 E 100
3,SUZB3,2024-01-26,52.91,2.04,2.14,-4.89,-4.89,18.85,51.89,53.17,"162,55 M",0.0204,51.852215,683452836,7.229463e+08,SUBIU,Suzano,Papel e Celulose,97,ENTRE 50 E 100
4,CPFE3,2024-01-26,37.10,2.03,2.49,-3.66,-3.66,20.70,36.37,37.32,"73,42 M",0.0203,36.361854,187732538,1.385740e+08,SUBIU,CPFL Energia,Energia,108,MAIS DE 100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-9.47,-13.98,-13.98,-32.72,10.70,11.08,"38,19 M",-0.0245,10.978985,533990587,-1.436355e+08,DESCEU,Carrefour Brasil,Varejo,46,MENOS DE 50
77,BHIA3,2024-01-26,8.70,-2.46,-6.95,-23.55,-23.55,-85.74,8.67,8.95,"27,54 M",-0.0246,8.919418,94843047,-2.081024e+07,DESCEU,Casas Bahia,Varejo,69,ENTRE 50 E 100
78,RENT3,2024-01-26,56.24,-3.63,-6.41,-11.57,-11.57,-2.77,56.04,58.90,"624,74 M",-0.0363,58.358410,853202347,-1.807433e+09,DESCEU,Localiza,Aluguel de carros,48,MENOS DE 50
79,CVCB3,2024-01-26,3.07,-4.36,-5.54,-12.29,-12.29,-36.83,3.05,3.23,"101,46 M",-0.0436,3.209954,525582771,-7.355741e+07,DESCEU,CVC,Viagens,49,MENOS DE 50
80,GOLL4,2024-01-26,5.92,-8.07,-15.91,-34.00,-34.00,-25.44,5.51,6.02,"154,36 M",-0.0807,6.439682,198184909,-1.029932e+08,DESCEU,GOL,Transporte Aéreo,20,MENOS DE 50

Vale prestar atenção no segundo parâmetro. Este segundo parâmetro pega a aba específica do arquivo.

In [4]:
df_acoesTotal = pd.read_excel("acoes_pura.xlsx", sheet_name="Total_de_acoes")
df_acoesTotal

                      Código  Qtde. Teórica
0                      RRRP3   2.356656e+08
1                      ALOS3   5.326166e+08
2                      ALPA4   1.767340e+08
3                      ABEV3   4.394246e+09
4                      ARZZ3   6.230589e+07
..                       ...            ...
84                     VBBR3   1.114413e+09
85                     WEGE3   1.481593e+09
86                     YDUQ3   2.893479e+08
87  Quantidade Teórica Total   9.637210e+10
88                   Redutor   1.704785e+07

[89 rows x 2 columns]

In [5]:
df_ticker = pd.read_excel("acoes_pura.xlsx", sheet_name="Ticker")
df_ticker

    Ticker            Nome
0    MGLU3  Magazine Luiza
1    HAPV3         Hapvida
2    PETR4       Petrobras
3    B3SA3              B3
4    USIM5        Usiminas
..     ...             ...
530  TKNO3           Tekno
531  COCE6          Coelce
532  MGEL3         Mangels
533  CTSA8      Santanense
534  MMAQ4   Minasmáquinas

[535 rows x 2 columns]

In [6]:
df_abaGPT = pd.read_excel("acoes_pura.xlsx", sheet_name="ChatGPT")
df_abaGPT

          Empresa          Segmento  Idade (anos)
0    3R Petroleum          Petróleo             9
1           ALOS3             Saúde            18
2      Alpargatas              Moda           113
3           Ambev         Alimentos            32
4          Arezzo              Moda            49
..            ...               ...           ...
79  Vibra Energia    Petróleo e Gás            68
80           Viva             Saúde            10
81           Vivo  Telecomunicações            27
82            WEG        Engenharia            60
83          YDUQS          Educação            55

[84 rows x 3 columns]

In [7]:
df_principal = df_principal[['Ativo', 'Data', 'Último (R$)', 'Var. Dia (%)']].copy()
df_principal

    Ativo       Data  Último (R$)  Var. Dia (%)
0   USIM5 2024-01-26         9.50          5.20
1   CMIN3 2024-01-26         6.82          2.40
2   PETR3 2024-01-26        41.96          2.19
3   SUZB3 2024-01-26        52.91          2.04
4   CPFE3 2024-01-26        37.10          2.03
..    ...        ...          ...           ...
76  CRFB3 2024-01-26        10.71         -2.45
77  BHIA3 2024-01-26         8.70         -2.46
78  RENT3 2024-01-26        56.24         -3.63
79  CVCB3 2024-01-26         3.07         -4.36
80  GOLL4 2024-01-26         5.92         -8.07

[81 rows x 4 columns]

In [8]:
df_principal = df_principal.rename(columns={'Último (R$)':'Valor_Final','Var. Dia (%)':'Var_Dia_pct'}).copy() # renomear as colunas para retirar os caracteres especiais
df_principal

    Ativo       Data  Valor_Final  Var_Dia_pct
0   USIM5 2024-01-26         9.50         5.20
1   CMIN3 2024-01-26         6.82         2.40
2   PETR3 2024-01-26        41.96         2.19
3   SUZB3 2024-01-26        52.91         2.04
4   CPFE3 2024-01-26        37.10         2.03
..    ...        ...          ...          ...
76  CRFB3 2024-01-26        10.71        -2.45
77  BHIA3 2024-01-26         8.70        -2.46
78  RENT3 2024-01-26        56.24        -3.63
79  CVCB3 2024-01-26         3.07        -4.36
80  GOLL4 2024-01-26         5.92        -8.07

[81 rows x 4 columns]

In [9]:
df_principal['Var_pct'] = df_principal['Var_Dia_pct'] / 100
df_principal['Var_Inicial'] = df_principal['Valor_Final'] / (1 + df_principal['Var_pct'])
df_principal

    Ativo       Data  Valor_Final  Var_Dia_pct  Var_pct  Var_Inicial
0   USIM5 2024-01-26         9.50         5.20   0.0520     9.030418
1   CMIN3 2024-01-26         6.82         2.40   0.0240     6.660156
2   PETR3 2024-01-26        41.96         2.19   0.0219    41.060769
3   SUZB3 2024-01-26        52.91         2.04   0.0204    51.852215
4   CPFE3 2024-01-26        37.10         2.03   0.0203    36.361854
..    ...        ...          ...          ...      ...          ...
76  CRFB3 2024-01-26        10.71        -2.45  -0.0245    10.978985
77  BHIA3 2024-01-26         8.70        -2.46  -0.0246     8.919418
78  RENT3 2024-01-26        56.24        -3.63  -0.0363    58.358410
79  CVCB3 2024-01-26         3.07        -4.36  -0.0436     3.209954
80  GOLL4 2024-01-26         5.92        -8.07  -0.0807     6.439682

[81 rows x 6 columns]

Agora, o problema requer que seja usado uma função semelhante ao `procv` do excel.

In [10]:
df_principal = df_principal.merge(df_acoesTotal, left_on='Ativo', right_on='Código', how='left')
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Código,Qtde. Teórica
0,USIM5,2024-01-26,9.50,5.20,0.0520,9.030418,USIM5,5.151174e+08
1,CMIN3,2024-01-26,6.82,2.40,0.0240,6.660156,CMIN3,1.110559e+09
2,PETR3,2024-01-26,41.96,2.19,0.0219,41.060769,PETR3,2.379878e+09
3,SUZB3,2024-01-26,52.91,2.04,0.0204,51.852215,SUZB3,6.834528e+08
4,CPFE3,2024-01-26,37.10,2.03,0.0203,36.361854,CPFE3,1.877325e+08
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.0245,10.978985,CRFB3,5.339906e+08
77,BHIA3,2024-01-26,8.70,-2.46,-0.0246,8.919418,BHIA3,9.484305e+07
78,RENT3,2024-01-26,56.24,-3.63,-0.0363,58.358410,RENT3,8.532023e+08
79,CVCB3,2024-01-26,3.07,-4.36,-0.0436,3.209954,CVCB3,5.255828e+08
80,GOLL4,2024-01-26,5.92,-8.07,-0.0807,6.439682,GOLL4,1.981849e+08

In [11]:
df_principal = df_principal.drop(columns=['Código'])
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde. Teórica
0,USIM5,2024-01-26,9.50,5.20,0.0520,9.030418,5.151174e+08
1,CMIN3,2024-01-26,6.82,2.40,0.0240,6.660156,1.110559e+09
2,PETR3,2024-01-26,41.96,2.19,0.0219,41.060769,2.379878e+09
3,SUZB3,2024-01-26,52.91,2.04,0.0204,51.852215,6.834528e+08
4,CPFE3,2024-01-26,37.10,2.03,0.0203,36.361854,1.877325e+08
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.0245,10.978985,5.339906e+08
77,BHIA3,2024-01-26,8.70,-2.46,-0.0246,8.919418,9.484305e+07
78,RENT3,2024-01-26,56.24,-3.63,-0.0363,58.358410,8.532023e+08
79,CVCB3,2024-01-26,3.07,-4.36,-0.0436,3.209954,5.255828e+08
80,GOLL4,2024-01-26,5.92,-8.07,-0.0807,6.439682,1.981849e+08

In [12]:
df_principal['Variacao_RS'] = (df_principal['Valor_Final'] - df_principal['Var_Inicial'])*df_principal['Qtde. Teórica']
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde. Teórica,Variacao_RS
0,USIM5,2024-01-26,9.50,5.20,0.0520,9.030418,5.151174e+08,2.418897e+08
1,CMIN3,2024-01-26,6.82,2.40,0.0240,6.660156,1.110559e+09,1.775160e+08
2,PETR3,2024-01-26,41.96,2.19,0.0219,41.060769,2.379878e+09,2.140059e+09
3,SUZB3,2024-01-26,52.91,2.04,0.0204,51.852215,6.834528e+08,7.229463e+08
4,CPFE3,2024-01-26,37.10,2.03,0.0203,36.361854,1.877325e+08,1.385740e+08
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.0245,10.978985,5.339906e+08,-1.436355e+08
77,BHIA3,2024-01-26,8.70,-2.46,-0.0246,8.919418,9.484305e+07,-2.081024e+07
78,RENT3,2024-01-26,56.24,-3.63,-0.0363,58.358410,8.532023e+08,-1.807433e+09
79,CVCB3,2024-01-26,3.07,-4.36,-0.0436,3.209954,5.255828e+08,-7.355741e+07
80,GOLL4,2024-01-26,5.92,-8.07,-0.0807,6.439682,1.981849e+08,-1.029932e+08

In [13]:
pd.options.display.float_format = '{:.2f}'.format # comando para ajustar como os números são mostrados
df_principal['Qtde. Teórica'] = df_principal['Qtde. Teórica'].astype(int)
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde. Teórica,Variacao_RS
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62

In [14]:
df_principal = df_principal.rename(columns={'Qtde. Teórica':'Qtde_Teorica'}).copy() # renomear a coluna para retirar os caracteres especiais
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62

In [15]:
df_principal['Resultado'] = df_principal['Variacao_RS'].apply(lambda x: 'Subiu' if x > 0 else('Desceu' if x < 0 else 'Estável'))
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS,Resultado
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu
...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu

In [16]:
df_principal = df_principal.merge(df_ticker, left_on='Ativo', right_on='Ticker', how='left')
df_principal = df_principal.drop(columns='Ticker')
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS,Resultado,Nome
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,Petrobras
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,Suzano
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia
...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu,CVC
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu,GOL

In [17]:
df_principal = df_principal.merge(df_abaGPT, left_on='Nome', right_on='Empresa', how='left')
df_principal = df_principal.drop(columns='Empresa')
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS,Resultado,Nome,Segmento,Idade (anos)
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,62
1,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,72
2,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,20
3,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,Petrobras,Petróleo,69
4,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,97
...,...,...,...,...,...,...,...,...,...,...,...,...
79,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,46
80,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,69
81,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Aluguel de carros,48
82,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Viagens,49
83,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Transporte Aéreo,20

In [18]:
df_principal['Cat_Idade'] = df_principal['Idade (anos)'].apply(lambda x: 'Mais de 100 anos' if x > 100 else('Menos de 50 anos' if x < 50 else 'Entre 50 e 100 anos'))
df_principal

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS,Resultado,Nome,Segmento,Idade (anos),Cat_Idade
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,62,Entre 50 e 100 anos
1,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,72,Entre 50 e 100 anos
2,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,20,Menos de 50 anos
3,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,Petrobras,Petróleo,69,Entre 50 e 100 anos
4,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,97,Entre 50 e 100 anos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,46,Menos de 50 anos
80,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,69,Entre 50 e 100 anos
81,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Aluguel de carros,48,Menos de 50 anos
82,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Viagens,49,Menos de 50 anos
83,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Transporte Aéreo,20,Menos de 50 anos

In [19]:
maior = df_principal['Variacao_RS'].max()
menor = df_principal['Variacao_RS'].min()
media = df_principal['Variacao_RS'].mean()
media_subiu = df_principal[df_principal['Resultado'] == 'Subiu']['Variacao_RS'].mean()
media_desceu = df_principal[df_principal['Resultado'] == 'Desceu']['Variacao_RS'].mean()

print(f'Maior R${maior:,.2f};\nMenor R${menor:,.2f};\nMédia R${media:,.2f};\nMédia subiu R${media_subiu:,.2f};\nMédia desceu R${media_desceu:,.2f}')

Maior R$4,762,926,995.25
;Menor R$-1,807,432,634.46;
Média R$221,607,084.56;
Média subiu R$530,932,235.41;
Média desceu R$-181,109,141.75

In [20]:
df_principal_subiu = df_principal[df_principal['Resultado'] == 'Subiu']
df_principal_subiu

,Ativo,Data,Valor_Final,Var_Dia_pct,Var_pct,Var_Inicial,Qtde_Teorica,Variacao_RS,Resultado,Nome,Segmento,Idade (anos),Cat_Idade
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,62,Entre 50 e 100 anos
1,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,72,Entre 50 e 100 anos
2,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,20,Menos de 50 anos
3,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,Petrobras,Petróleo,69,Entre 50 e 100 anos
4,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,97,Entre 50 e 100 anos
5,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia,108,Mais de 100 anos
6,PRIO3,2024-01-26,45.69,1.98,0.02,44.80,800010734,709687498.18,Subiu,PetroRio,Petróleo,8,Menos de 50 anos
7,PETR4,2024-01-26,39.96,1.73,0.02,39.28,-2147483648,3103136291.22,Subiu,Petrobras,Petróleo,69,Entre 50 e 100 anos
8,VALE3,2024-01-26,69.50,1.66,0.02,68.37,-2147483648,4762926995.25,Subiu,Vale,Mineração,80,Entre 50 e 100 anos
9,VALE3,2024-01-26,69.50,1.66,0.02,68.37,-2147483648,4762926995.25,Subiu,Vale,Mineração,75,Entre 50 e 100 anos
10,MULT3,2024-01-26,28.19,1.58,0.02,27.75,268505432,117732680.08,Subiu,Multiplan,Imobiliário,52,Entre 50 e 100 anos
11,ITUB4,2024-01-26,32.81,1.48,0.01,32.33,-2147483648,2297591984.33,Subiu,Itaú Unibanco,Financeiro,13,Menos de 50 anos
12,RDOR3,2024-01-26,27.56,1.43,0.01,27.17,1168230366,453917907.01,Subiu,Rede D'Or,Saúde,50,Entre 50 e 100 anos
13,BRKM5,2024-01-26,18.55,1.42,0.01,18.29,265877867,69054317.64,Subiu,Braskem,Química,21,Menos de 50 anos
14,AZUL4,2024-01-26,14.27,1.42,0.01,14.07,327593725,65452205.55,Subiu,Azul,Transporte Aéreo,14,Menos de 50 anos
15,RRRP3,2024-01-26,28.75,1.41,0.01,28.35,235665566,94204643.35,Subiu,3R Petroleum,Petróleo,9,Menos de 50 anos
16,EQTL3,2024-01-26,35.32,1.34,0.01,34.85,1095587251,511671895.45,Subiu,Equatorial Energia,Energia,23,Menos de 50 anos
17,CSNA3,2024-01-26,18.16,1.33,0.01,17.92,600865451,143220991.46,Subiu,Siderúrgica Nacional,Siderurgia,80,Entre 50 e 100 anos
18,YDUQ3,2024-01-26,19.77,1.28,0.01,19.52,289347914,72295838.99,Subiu,YDUQS,Educação,55,Entre 50 e 100 anos
19,UGPA3,2024-01-26,28.31,1.28,0.01,27.95,1086411192,388705223.96,Subiu,Ultrapar,Petróleo e Gás,88,Entre 50 e 100 anos
20,MRVE3,2024-01-26,8.08,1.25,0.01,7.98,376187582,37525872.38,Subiu,MRV,Construção,41,Menos de 50 anos
21,ARZZ3,2024-01-26,57.91,1.15,0.01,57.25,62305891,41021792.09,Subiu,Arezzo,Moda,49,Menos de 50 anos
22,BBDC4,2024-01-26,15.52,1.04,0.01,15.36,-2147483648,822148336.41,Subiu,Banco Bradesco,Financeiro,78,Entre 50 e 100 anos
23,BEEF3,2024-01-26,7.19,0.98,0.01,7.12,261036182,18214628.10,Subiu,Minerva,Alimentos,30,Menos de 50 anos
24,PCAR3,2024-01-26,4.14,0.97,0.01,4.10,159430826,6340916.22,Subiu,Grupo Pão de Açúcar,Varejo,71,Entre 50 e 100 anos
25,BRFS3,2024-01-26,14.61,0.96,0.01,14.47,1677525446,233045769.57,Subiu,BRF,Alimentos,86,Entre 50 e 100 anos
26,VIVT3,2024-01-26,51.20,0.88,0.01,50.75,423091712,188965307.06,Subiu,Vivo,Telecomunicações,27,Menos de 50 anos
27,RAIL3,2024-01-26,22.64,0.84,0.01,22.45,1218352541,229771333.63,Subiu,Rumo,Transporte,9,Menos de 50 anos
28,RAIL3,2024-01-26,22.64,0.84,0.01,22.45,1218352541,229771333.63,Subiu,Rumo,Logística,28,Menos de 50 anos
29,CIEL3,2024-01-26,4.90,0.82,0.01,4.86,1095462329,43657683.38,Subiu,Cielo,FinTech,23,Menos de 50 anos
30,DXCO3,2024-01-26,7.81,0.77,0.01,7.75,302768240,18068446.61,Subiu,Dexco,Metalurgia,19,Menos de 50 anos
31,TIMS3,2024-01-26,17.52,0.74,0.01,17.39,807896814,103972807.37,Subiu,TIM,Telecomunicações,27,Menos de 50 anos
32,BRAP4,2024-01-26,23.22,0.73,0.01,23.05,251003438,42238249.54,Subiu,Bradespar,Financeiro,31,Menos de 50 anos
33,LWSA3,2024-01-26,5.55,0.72,0.01,5.51,393173139,15598886.65,Subiu,Locaweb,Tecnologia,24,Menos de 50 anos
34,RECV3,2024-01-26,23.83,0.71,0.01,23.66,275005663,46201006.00,Subiu,PetroRecôncavo,Petróleo,10,Menos de 50 anos
35,ITSA4,2024-01-26,10.01,0.70,0.01,9.94,-2147483648,373853994.88,Subiu,Itaúsa,Financeiro,53,Entre 50 e 100 anos
36,BBAS3,2024-01-26,56.97,0.68,0.01,56.59,1420949112,546752087.99,Subiu,Banco do Brasil,Financeiro,214,Mais de 100 anos
37,RADL3,2024-01-26,26.16,0.61,0.01,26.00,1275798515,202352473.74,Subiu,RaiaDrogasil,Saúde,119,Mais de 100 anos
38,GOAU4,2024-01-26,10.08,0.59,0.01,10.02,660411219,39045606.94,Subiu,Metalúrgica Gerdau,Siderurgia,120,Mais de 100 anos
39,CSAN3,2024-01-26,18.57,0.59,0.01,18.46,1168097881,127229653.18,Subiu,Cosan,Energia,25,Menos de 50 anos
40,JBSS3,2024-01-26,24.34,0.57,0.01,24.20,1134986472,156573285.43,Subiu,JBS,Alimentos,68,Entre 50 e 100 anos
41,MGLU3,2024-01-26,2.08,0.48,0.00,2.07,-2147483648,28493619.27,Subiu,Magazine Luiza,Varejo,64,Entre 50 e 100 anos
42,BBDC3,2024-01-26,13.75,0.36,0.00,13.70,1500728902,74019610.05,Subiu,Banco Bradesco,Financeiro,78,Entre 50 e 100 anos
43,GGBR4,2024-01-26,21.84,0.27,0.00,21.78,1118525506,65779607.10,Subiu,Gerdau,Siderurgia,120,Mais de 100 anos
44,RAIZ4,2024-01-26,3.74,0.26,0.00,3.73,1193047233,11571106.42,Subiu,Raízen,Energia,11,Menos de 50 anos
45,CPLE6,2024-01-26,10.07,0.19,0.00,10.05,1679335290,32069789.50,Subiu,Copel,Energia,65,Entre 50 e 100 anos
46,VAMO3,2024-01-26,8.18,0.12,0.00,8.17,421383330,4131341.16,Subiu,Grupo Vamos,Logística,4,Menos de 50 anos

In [21]:
df_analise_segmento = df_principal_subiu.groupby('Segmento')['Variacao_RS'].sum().reset_index()
df_analise_segmento

            Segmento   Variacao_RS
0          Alimentos  407833683.09
1         Construção   37525872.38
2           Educação   72295838.99
3            Energia  821116399.61
4            FinTech   43657683.38
5         Financeiro 4156604263.21
6        Imobiliário  117732680.08
7          Logística  233902674.79
8         Metalurgia   18068446.61
9          Mineração 9703369960.80
10              Moda   41021792.09
11  Papel e Celulose  722946282.71
12          Petróleo 6093288832.26
13    Petróleo e Gás  388705223.96
14           Química   69054317.64
15             Saúde  656270380.75
16        Siderurgia  731825656.36
17        Tecnologia   15598886.65
18  Telecomunicações  292938114.42
19        Transporte  229771333.63
20  Transporte Aéreo   65452205.55
21            Varejo   34834535.50

In [22]:
df_analise_saldo = df_principal.groupby('Resultado')['Variacao_RS'].sum().reset_index()
df_analise_saldo

  Resultado    Variacao_RS
0    Desceu -6338819961.32
1   Estável           0.00
2     Subiu 24953815064.46

Criação de gráficos.

In [23]:
fig = px.bar(df_analise_saldo, x='Resultado', y='Variacao_RS', text='Variacao_RS', title='Variação R$ por resultado')
fig.show()